make.sh started at 2024-09-12 08:52:56
Executing: bash my_shell_script.sh
Executing: python wrangle_data.py
Traceback (most recent call last):
  File "C:\Users\chadi\Dropbox\GentzkowLabTemplate\1_data\source\wrangle_data.py", line 22, in <module>
    main()
  File "C:\Users\chadi\Dropbox\GentzkowLabTemplate\1_data\source\wrangle_data.py", line 11, in main
    mpg = pd.read_csv("../input/mpg.csv")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chadi\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chadi\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chadi\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chadi\anaconda3\Lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\chadi\anaconda3\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../input/mpg.csv'
make.sh finished at 2024-09-12 08:52:57
